# In deiner .github/workflows/ci.yml

# Ändere diese Zeile:
- name: Setup Node.js
  uses: actions/setup-node@v3
  with:
    node-version: 16  # <-- Hier liegt das Problem
    cache: 'npm'

# Zu dieser:
- name: Setup Node.js
  uses: actions/setup-node@v3
  with:
    node-version: 18  # <-- Auf Version 18 aktualisieren
    cache: 'npm'